### ISSUE TITLE
Steps to reproduce when using airpwn-ng

### ISSUE THREAD

**Issue by CHillyVibes** [ICSec/airpwn-ng#21]
Adding on to commands being used now after installing those packages except scapy in the python2 folder

sudo airodump-ng wlan0 --band b --bssid * --channel *
sudo airtun-ng -a * -e * -p * wlan0
sudo ifconfig at0 192.168.1.83 netmask 255.255.255.0 up
sudo aireplay-ng wlan0 -a * -c * -0 1

sudo python3 ./airpwn-ng -i at0 -m wlan0 --injection payloads/demo

:(

Im having an issue installing scapy scapy-2.3.1.tar.gz

I have scapy installed 2.4.5

I'm trying to attack my wpa protected network

    Closing this out as inactive -- Feel free to re-open @tuphr1928

Linux Bebo 5.18.0-kali5-amd64 https://github.com/ICSec/airpwn-ng/issues/1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07) x86_64 GNU/Linux

sudo python -m pip install *.tar.gz

Processing ./pbkdf2-1.3.tar.gz
Preparing metadata (setup.py) ... done
Processing ./pycryptodomex-3.4.5.tar.gz
Preparing metadata (setup.py) ... done
Processing ./pyDot11-1.0.2.2.tar.gz
Preparing metadata (setup.py) ... done
Processing ./rc4-0.1.tar.gz
Preparing metadata (setup.py) ... done
Processing ./scapy-2.3.1.tar.gz
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [7 lines of output]
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "/tmp/pip-req-build-soowjubg/setup.py", line 35
os.chmod(fname,0755)
^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

pycryptodomex-3.4.5.tar.gz

installing package worked whats the issue? with scapy if the github repo says we dont need to do anything else?????

/home/kali/airpwn-ng/_archive/_python2/RESOURCEs

Airpwn-ng will load now but it will say warning 58 back pressure???

please make a tutorial for installation and usage thank you

**Comment by stryngs** [comment]
Hi @CHillyVibes,

I ended up deprecating the pyDot11 approach for airpwn-ng.  To leverage against WPA2 I have an example written here:
https://github.com/ICSec/airpwn-ng#example-usage

Does the airtun-ng approach suite your needs or are you needing the pyDot11 approach?

**Comment by ChillVibesMushroom** [comment]
> Hi @CHillyVibes,
> 
> I ended up deprecating the pyDot11 approach for airpwn-ng. To leverage against WPA2 I have an example written here: https://github.com/ICSec/airpwn-ng#example-usage
> 
> Does the airtun-ng approach suite your needs or are you needing the pyDot11 approach?

Hey what's up man this is one of my original accounts actually I'm up and coming right now I have a lot going on and airtun-ng is decent I just can't figure out how to inject script code OTA I know I can capture with airodump-ng and use airtun-ng but I noticed when I also run airpwn-ng it gives me an error about pressure and what not ? it won't even show cookie info or anything info wise even when visiting vuln web?

**Comment by ChillVibesMushroom** [comment]
Is there a course available I can take online or from you that can explain this more in depth and also when installing airpwn-ng it messed up my mitm tools that I had to do a system reinstall :(

**Comment by stryngs** [comment]
The only thing you "install" for airpwn-ng is:
python3 -m pip install RESOURCEs/airpwn-ng-*.tar.gz

That tarball is a wrapper for:
https://github.com/ICSec/airpwn-ng/tree/main/SRC/airpwn_ng/lib

Nothing in that code would ruin your system.  Feel free to read it over and see for yourself.

When you're running airpwn-ng are you using the steps from the readme?

**Comment by ChillVibesMushroom** [comment]
But what if it messes up scary which is at 2.5 then in doing that it messed up bettercap 2 by evil socket man and i really just want this to work correctly

**Comment by ChillVibesMushroom** [comment]
Is there a way to use airtun-ng on an OPN wifi network :( I've been trying and I've been baffled I Ned your help man

**Comment by stryngs** [comment]
Have you tried the example syntax here?
https://github.com/ICSec/airpwn-ng#example-usage

**Comment by ChillVibesMushroom** [comment]
> Have you tried the example syntax here? https://github.com/ICSec/airpwn-ng#example-usage

But I just want to be able to capture the traffic without script injection

**Comment by ChillVibesMushroom** [comment]
like using airtun-ng but that requires a password and it doesn't allow me to use it without a password :( how would I do that

**Comment by ChillVibesMushroom** [comment]
I can put airpwn-ng in the virtual envrionment so it doesn't conflict with packages I already have in use right like scapy? which is used for other things?


![venv](https://user-images.githubusercontent.com/99580833/230037236-18c5de0f-01a2-436b-bbef-9c889888f8ec.png)

**Comment by ChillVibesMushroom** [comment]
I followed your process with the tar file in Resources then I ran this because I got the error below

 python3 ./setup.py install
running install
/home/kali/eevee/eevee/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/kali/eevee/eevee/lib/python3.11/site-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating airpwn_ng.egg-info
writing airpwn_ng.egg-info/PKG-INFO
writing dependency_links to airpwn_ng.egg-info/dependency_links.txt
writing requirements to airpwn_ng.egg-info/requires.txt
writing top-level names to airpwn_ng.egg-info/top_level.txt
writing manifest file 'airpwn_ng.egg-info/SOURCES.txt'
package init file 'airpwn_ng/__init__.py' not found (or not a regular file)
package init file 'airpwn_ng/lib/__init__.py' not found (or not a regular file)
reading manifest file 'airpwn_ng.egg-info/SOURCES.txt'
writing manifest file 'airpwn_ng.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/airpwn_ng
creating build/lib/airpwn_ng/lib
copying airpwn_ng/lib/parameters.py -> build/lib/airpwn_ng/lib
copying airpwn_ng/lib/core.py -> build/lib/airpwn_ng/lib
copying airpwn_ng/lib/menu.py -> build/lib/airpwn_ng/lib
copying airpwn_ng/lib/sniffer.py -> build/lib/airpwn_ng/lib
copying airpwn_ng/lib/injector.py -> build/lib/airpwn_ng/lib
copying airpwn_ng/lib/visuals.py -> build/lib/airpwn_ng/lib
copying airpwn_ng/lib/packet_handler.py -> build/lib/airpwn_ng/lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/airpwn_ng
creating build/bdist.linux-x86_64/egg/airpwn_ng/lib
copying build/lib/airpwn_ng/lib/parameters.py -> build/bdist.linux-x86_64/egg/airpwn_ng/lib
copying build/lib/airpwn_ng/lib/core.py -> build/bdist.linux-x86_64/egg/airpwn_ng/lib
copying build/lib/airpwn_ng/lib/menu.py -> build/bdist.linux-x86_64/egg/airpwn_ng/lib
copying build/lib/airpwn_ng/lib/sniffer.py -> build/bdist.linux-x86_64/egg/airpwn_ng/lib
copying build/lib/airpwn_ng/lib/injector.py -> build/bdist.linux-x86_64/egg/airpwn_ng/lib
copying build/lib/airpwn_ng/lib/visuals.py -> build/bdist.linux-x86_64/egg/airpwn_ng/lib
copying build/lib/airpwn_ng/lib/packet_handler.py -> build/bdist.linux-x86_64/egg/airpwn_ng/lib
byte-compiling build/bdist.linux-x86_64/egg/airpwn_ng/lib/parameters.py to parameters.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/airpwn_ng/lib/core.py to core.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/airpwn_ng/lib/menu.py to menu.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/airpwn_ng/lib/sniffer.py to sniffer.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/airpwn_ng/lib/injector.py to injector.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/airpwn_ng/lib/visuals.py to visuals.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/airpwn_ng/lib/packet_handler.py to packet_handler.cpython-311.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying airpwn_ng.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying airpwn_ng.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying airpwn_ng.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying airpwn_ng.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying airpwn_ng.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/airpwn_ng-2.0.8-py3.11.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing airpwn_ng-2.0.8-py3.11.egg
Copying airpwn_ng-2.0.8-py3.11.egg to /home/kali/eevee/eevee/lib/python3.11/site-packages
Adding airpwn-ng 2.0.8 to easy-install.pth file

Installed /home/kali/eevee/eevee/lib/python3.11/site-packages/airpwn_ng-2.0.8-py3.11.egg
Processing dependencies for airpwn-ng==2.0.8
Searching for scapy==2.4.5
Best match: scapy 2.4.5
Adding scapy 2.4.5 to easy-install.pth file
Installing UTscapy script to /home/kali/eevee/eevee/bin
Installing scapy script to /home/kali/eevee/eevee/bin

Using /home/kali/eevee/eevee/lib/python3.11/site-packages
Finished processing dependencies for airpwn-ng==2.0.8

This is the error I recieved.


sudo ./airpwn-ng -i wlan1mon -m wlan1mon --injection payloads/demo
Traceback (most recent call last):
  File "/home/kali/eevee/airpwn-ng/./airpwn-ng", line 8, in <module>
    from airpwn_ng.lib.core import Core
ModuleNotFoundError: No module named 'airpwn_ng'

**Comment by ChillVibesMushroom** [comment]
![dependencies](https://user-images.githubusercontent.com/99580833/230080479-884093d5-c576-4a45-8050-e4e8a1eb1517.png)

**Comment by stryngs** [comment]
Check out the install instructions, you did added steps and I don't account for anything other than whats listed here:
https://github.com/ICSec/airpwn-ng#installation

That being said I do see an issue I had not thought of.  I'll get a PR done tonight.

**Comment by stryngs** [comment]
I did testing tonight @ChillVibesMushroom.  I'm currently working on an [edgedressing](https://github.com/stryngs/edgedressing) concept and used tonight to verify some of the basics of airpwn-ng.  It worked just as expected.  If it were me I would start testing using an Open network.  That is by far the fastest way airpwn-ng can operate.  If possible, slow it down to B speeds just in case your computer is not fast enough to keep up, etc.

Once you've gotten it working on Open then flip to wep and wpa for a more real world scenario.

Let me know the results of your testing in open.

Please re-read the whole README, it works flawless for myself and others.  Not sure of the root cause for your issues yet.

**Comment by ChillVibesMushroom** [comment]
Wow you should let us know we have to type python3 ./airpwn-ng man I was literally baffled by this lol

can I create a tutorial for thos that need a tutorial on how to run airpwn-ng in a controlled environment for those people who don't want to mess with packages they already have installed?


![airpwn-ngworks](https://user-images.githubusercontent.com/99580833/230672729-c6c2e90f-1a57-42d4-9283-2043a92396d3.png)

**Comment by ChillVibesMushroom** [comment]
Is this how we would use one NIC

python3 ./airpwn-ng -i wlan1mon -m wlan1mon --injection payloads/demo 


Then we visit any site on the OPN network that's http and what loads is the demo payload?

**Comment by ChillVibesMushroom** [comment]
> Check out the install instructions, you did added steps and I don't account for anything other than whats listed here: https://github.com/ICSec/airpwn-ng#installation
> 
> That being said I do see an issue I had not thought of. I'll get a PR done tonight.

actually though it is my bad I was thinking bash scripts when I was executing but cut me some slack man I have Pleurisy for some reason and I'm actually trying to just get this done since I can't go to work man this tool is awesome I can't wait to finally go out there and use it as soon as I get better.

**Comment by stryngs** [comment]
@ChillVibesMushroom did this solve your concerns?

**Comment by ChillVibesMushroom** [comment]
> @ChillVibesMushroom did this solve your concerns?

Yes it did am I running this correctly

Is this how we would use one NIC

My opn network run off wifi pineapple 

python3 ./airpwn-ng -i wlan1mon -m wlan1mon --injection payloads/demo

Then we visit any site on the OPN network that's http and what loads is the demo payload?

**Comment by stryngs** [comment]
I am glad it worked out for you.  You'd be surprised at what runs http these days.. =(

**Comment by ChillVibesMushroom** [comment]
> I am glad it worked out for you.  You'd be surprised at what runs http these days.. =(
> 
> 

I still haven't gotten around to use it because I've been working long shifts and researching analyzing packets with Wireshark

Do you have any scripts that you can send me in regards to airpwn payloads

**Comment by ChillVibesMushroom** [comment]
Hey I was wondering why the demo payload doesn't work when I visit vulnweb.com http site 

Do I have to Deauthenticate before I visit the site ?

**Comment by stryngs** [comment]
I would recommend using something like tcpdump or wireshark to capture the traffic with a 3rd device.  From there you'll be able to see how things play out in real time without adding more overhead to your computer.

Depending on the specs of your machine, which version of python, etc, etc, you may just be losing the tcp race.

Is the network open, wep, wpa2, etc..

I'd need to know more about your setup to help you understand why you're not winning the race.

**Comment by ChillVibesMushroom** [comment]
> I would recommend using something like tcpdump or wireshark to capture the traffic with a 3rd device. From there you'll be able to see how things play out in real time without adding more overhead to your computer.
> 
> Depending on the specs of your machine, which version of python, etc, etc, you may just be losing the tcp race.
> 
> Is the network open, wep, wpa2, etc..
> 
> I'd need to know more about your setup to help you understand why you're not winning the race.

it's an open network 
I'm running airpwn-ng using one nic thats in monitor mode and the payload is the default payload I'm not DOSing im just refreshing the page

**Comment by stryngs** [comment]
If you are on an open network that is by far the fastest way of doing things.

When you refresh the page on the target machine, does airpwn-ng show any activity?
