### ISSUE TITLE
Some ideas for the performance issue

### ISSUE THREAD

**Issue by xmnr** [ICSec/airpwn-ng#6]
Howdy,

I don't have an extra wifi card on me, so I can't test these, but:

1. Maybe we could speed up file IO by reading and writing to a ramfs?
2. I don't fully understand the codebase yet, but do we need to run a new instance of tcpdump every time? could we get away with running one in the backgroup and tailing the log or something?

**Comment by stryngs** [comment]
- ramfs, interesting idea.  Never used one so I'll have to research, but will definitely look into that.

- tcpdump is required to start anew with each loop because of how the engine parses the LOG file.
  - I would love to find a way to keep it running without having to restart it, but I don't see that as a speed issue because so long as it is running, when it reflips it's not an issue.  You're going to catch the packets, it's the inject that needs to be speedy...

Thank you for your input!

**Comment by stryngs** [comment]
Didn't mean to close, not done with ramfs!

**Comment by fstd** [comment]
Linux calls that "tmpfs" nowadays and you have probably mounted one on /tmp already

**Comment by Jack64** [comment]
RAMFS (TMPFS) implemented.

**Comment by Jack64** [comment]
Closed this accidentally, this is not just about RAMFS.
Other performance improvements implemented:
- Packet injection via monitor mode so the packet doesn't need to be routed any more.

We welcome any input concerning performance improvement.

**Comment by stryngs** [comment]
Long live the airpwn-ng =)

**Comment by stryngs** [comment]
Closing out as airpwn-ng is no longer using tcpdump or bash.  Now it only needs Python "goodies" to make better...
